### ISSUE TITLE
Card linker unable to distinguish 2 cards with same title from different sides

### ISSUE THREAD

**Issue by mcarulli** [swccgpc/DiscordCardLinker#4]
If you enter a card title that is shared by both sides (such as a location), it will only show one of them. No way to show both. For example, typing "[Naboo: Battle Plains]" will only show LS battle plains.

**Comment by DevoKun** [comment]
resolved

**Comment by mcarulli** [comment]
@DevoKun not sure if related but [tatooine] doesn't work with the bot at all now, but [naboo] does. The react menu also works, but it's just tatooine so far that I've found doesn't work at all. Maybe because there are 4 different versions?
